# Generated by Django 4.1.3 on 2022-11-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('step_video', models.URLField(blank=True, max_length=255, null=True)),
                ('step_image', models.URLField(blank=True, max_length=255, null=True)),
                ('job_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobscope')),
            ],
        ),
    ]
