# Generated by Django 4.1.3 on 2022-12-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobscope",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="video/%y"),
        ),
    ]
